model:
  default_preset: gpt-4-chatbot-responses
  # default_preset: claude-chatbot-responses
  # default_preset: mistral-large
chat:
  log:
    enabled: true
    # Provide as CLI arg, /dev/null is used here to prevent.
    # the file from being written if it's turned on in a
    # default Config().
    filepath: /dev/null
debug:
  log:
    enabled: true
plugins:
  enabled:
    # - awesome
    # - database
    # - data_query
    # - echo
    # - pastebin
    - gist
    # - examples
    - shell
    # - test
    # - provider_ai21
    # - provider_cohere
    # - provider_huggingface_hub
    # - provider_openai
    - provider_fake_llm
    # - provider_azure_openai_chat
    - provider_chat_anthropic
    # - provider_chat_anyscale
    # - provider_chat_cohere
    - provider_chat_ollama
    # - provider_chat_vertexai
    # - provider_chat_google_genai
    # - provider_chat_groq
    # - provider_chat_mistralai
    - provider_openrouter
    - provider_chat_fireworks
    # - provider_vertexai
  examples:
    confirm_overwrite: false
  pastebin:
    include_raw_link: true
    exclude_system_messages: true
  gist:
    include_raw_link: true
    exclude_system_messages: true
  provider_chat_fireworks:
    models:
      "accounts/fireworks/models/mixtral-8x22b-instruct":
        max_tokens: 65536
      "accounts/fireworks/models/llama-v3-70b-instruct":
        max_tokens: 8192
      "accounts/fireworks/models/firefunction-v1":
        max_tokens: 32768
  provider_chat_groq:
    show_inactive_models: true
