backend: browser
browser:
  provider: firefox
  plugins:
    - plugin-d1d6eb04-3375-40aa-940a-c2fc57ce0f51
model:
  default_preset: gpt-4-browsing
  #default_preset: gpt-4-plugins
  # default_preset: gpt-4
chat:
  log:
    enabled: true
    # Provide as CLI arg.
    # filepath: None
debug:
  log:
    enabled: true
plugins:
  enabled:
    - awesome
    - echo
    - shell
