---
- name: "Generate personas based on a provided 'characteristics' JSON spec."
  hosts: localhost
  gather_facts: no
  vars:
    profile: "uptrust"
    preset: "gpt-4-creative-writing"
    url: "https://f.xylil.com/uptrust/uptrust-persona-characteristics.json"
    #url: "https://raw.githubusercontent.com/daveshap/Automated_Consensus/main/persona_traits.json"
    iterations: 30
    output_dir: "/tmp/personas"
    db_login_host: localhost
    db_name: uptrust
    db_login_user: general
    db_login_password: general

  tasks:
    - name: "Retrieve JSON persona data from URL: {{ url }}"
      uri:
        url: "{{ url }}"
        return_content: yes
      register: result

    - name: Convert JSON data to usable format
      set_fact:
        data: "{{ result.content | from_json }}"

    - name: Loop to generate personas
      loop: "{{ range(1, iterations | int + 1) }}"
      loop_control:
        loop_var: iteration
      vars:
        iteration: "{{ item }}"
      include_tasks: persona-generator-create-persona.yaml
...
