backend: api
model:
  default_preset: gpt-4-chatbot-responses
chat:
  log:
    enabled: true
    # Provide as CLI arg, /dev/null is used here to prevent.
    # the file from being written if it's turned on in a
    # default Config().
    filepath: /dev/null
debug:
  log:
    enabled: true
plugins:
  enabled:
    - pastebin
    #- examples
  examples:
    confirm_overwrite: false
